from pydantic import BaseModel, Field
from typing import Optional
from datetime import date, datetime

class Project(BaseModel):
    """
    Pydantic model defining the Project schema with field aliases for consistent frontend-backend mapping.
    Optional fields and defaults added for creation flexibility.
    """
    id: Optional[str] = Field(None, description="Unique project ID, auto-generated by Supabase")
    
    project_name: str = Field(..., alias='name', description="The name of the project")
    client_name: str = Field(..., alias='client', description="The name of the client")

    completion_pct: int = Field(0, alias='completion', ge=0, le=100, description="Completion percentage (0-100)")

    start_date: date = Field(..., description="Project start date")
    deadline: date = Field(..., description="Project deadline")

    status: Optional[str] = Field(None, description="Current status of the project (e.g., On Track)")

    budget: Optional[int] = Field(None, description="Project budget")
    owner: Optional[str] = Field(None, description="The owner or manager of the project")

    created_at: Optional[datetime] = Field(None, description="Timestamp of creation")
    updated_at: Optional[datetime] = Field(None, description="Timestamp of last update")

    class Config:
        populate_by_name = True
        from_attributes = True
        json_schema_extra = {
            "example": {
                # id excluded because it's auto-generated on create
                "project_name": "Website Redesign",
                "client_name": "TechCorp Inc",
                "start_date": "2024-01-15",
                "deadline": "2024-03-15",
                "completion_pct": 85,
                "status": "On Track",
                "budget": 50000,
                "owner": "Jane Doe",
                # timestamps excluded on create
            }
        }

# --- THIS IS THE NEW MODEL FOR HANDLING UPDATES ---
class ProjectUpdate(BaseModel):
    """
    A separate model for updates, where all fields are optional.
    This allows a user to update only the fields they want to change.
    """
    project_name: Optional[str] = Field(None, alias='name')
    client_name: Optional[str] = Field(None, alias='client')
    completion_pct: Optional[int] = Field(None, alias='completion', ge=0, le=100)
    deadline: Optional[date] = None
    budget: Optional[int] = None
    owner: Optional[str] = None
    start_date: Optional[date] = None # Added to ensure it can be updated if needed

    class Config:
        populate_by_name = True
