# --- This is the complete, final, and fully enhanced file for your report generation logic. ---

from fastapi import APIRouter, HTTPException, status, BackgroundTasks, Depends
from typing import List, Dict
from uuid import uuid4
from datetime import datetime
import io

# PDF Generation library and utilities
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table, TableStyle
from reportlab.lib import colors

# Import services, models, and security
from app.services.database import db_service, supabase
from app.models.report_model import Report, ReportCreate
from app.services.auth import get_current_user

router = APIRouter()

# --- PDF Generation Helper Functions (Unchanged) ---

def draw_header(p, title, user_email):
    """Draws a standardized header on a PDF canvas."""
    width, height = letter
    p.setFont("Helvetica-Bold", 18)
    p.drawString(inch, height - inch, title)
    p.setFont("Helvetica", 10)
    p.drawString(inch, height - 1.25 * inch, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    p.drawString(inch, height - 1.40 * inch, f"Generated by: {user_email}")
    p.line(inch, height - 1.55 * inch, width - inch, height - 1.55 * inch)
    return height - 2 * inch # Return starting y_position

def create_summary_pdf(metrics: dict, user_email: str) -> io.BytesIO:
    """Creates the Executive Summary PDF (already implemented and working)."""
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    y_position = draw_header(p, "Executive Summary Report", user_email)

    styles = getSampleStyleSheet()
    
    # Project KPIs
    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch, y_position, "Project Health")
    y_position -= 0.3 * inch
    project_stats = metrics.get('project_stats', {})
    project_kpis = [ f"<b>Total Projects:</b> {project_stats.get('total_projects', 0)}", f"<b>Active Projects:</b> {project_stats.get('active_projects', 0)}", f"<b>- On Track:</b> {project_stats.get('on_track', 0)}", f"<b>- At Risk:</b> {project_stats.get('at_risk', 0)}", f"<b>- Delayed:</b> {project_stats.get('delayed', 0)}" ]
    for kpi in project_kpis:
        para = Paragraph(kpi, styles['Normal'])
        para.wrapOn(p, 5 * inch, 10 * inch)
        para.drawOn(p, 1.2 * inch, y_position)
        y_position -= para.height + 5

    y_position -= 0.5 * inch
    
    # Sales & Leads KPIs
    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch, y_position, "Sales & Leads Performance")
    y_position -= 0.3 * inch
    lead_stats = metrics.get('lead_stats', {})
    lead_kpis = [ f"<b>Total Leads:</b> {lead_stats.get('total_leads', 0)}", f"<b>Pipeline Value (Active):</b> ₹{lead_stats.get('pipeline_value', 0):,}", f"<b>Total Revenue (Won):</b> ₹{lead_stats.get('total_revenue', 0):,}", f"<b>Conversion Rate:</b> {lead_stats.get('conversion_rate', 0)}%" ]
    for kpi in lead_kpis:
        para = Paragraph(kpi, styles['Normal'])
        para.wrapOn(p, 5 * inch, 10 * inch)
        para.drawOn(p, 1.2 * inch, y_position)
        y_position -= para.height + 5

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

def create_project_health_pdf(projects: List[Dict], user_email: str) -> io.BytesIO:
    """
    FEATURE: Generates a detailed, multi-page Project Health PDF with tables.
    """
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=landscape(letter)) # Use landscape for wider tables
    width, height = landscape(letter)
    
    y_position = draw_header(p, "Project Health Report", user_email)

    statuses_to_report = ["On Track", "At Risk", "Delayed", "Completed"]
    
    for status in statuses_to_report:
        projects_in_status = [proj for proj in projects if proj.get('status') == status]
        if not projects_in_status:
            continue

        p.setFont("Helvetica-Bold", 14)
        p.drawString(inch, y_position, f"Status: {status} ({len(projects_in_status)} Projects)")
        y_position -= 0.4 * inch

        table_data = [
            ["Project Name", "Client", "Owner", "Completion", "Budget (INR)"]
        ]
        for proj in projects_in_status:
            table_data.append([
                proj.get('name', '-'),
                proj.get('client', '-'),
                proj.get('owner', '-'),
                f"{proj.get('completion', 0)}%",
                f"₹{proj.get('budget', 0):,}"
            ])
        
        table = Table(table_data, colWidths=[2.5*inch, 2*inch, 1.5*inch, 1*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))

        # Check if table fits on page, otherwise start a new page
        table_height = table.wrap(width - 2*inch, height)[1]
        if y_position - table_height < inch:
            p.showPage()
            y_position = height - 1.5 * inch

        table.drawOn(p, inch, y_position - table_height)
        y_position -= table_height + 0.5 * inch

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

def create_leads_sales_pdf(leads: List[Dict], lead_stats: dict, user_email: str) -> io.BytesIO:
    """
    FEATURE: Generates a detailed Leads & Sales PDF.
    """
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    y_position = draw_header(p, "Leads & Sales Funnel Report", user_email)

    # Summary KPIs
    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch, y_position, "Overall Performance")
    y_position -= 0.3 * inch
    styles = getSampleStyleSheet()
    summary_kpis = [
        f"<b>Total Leads:</b> {lead_stats.get('total_leads', 0)}",
        f"<b>Pipeline Value (Active):</b> ₹{lead_stats.get('pipeline_value', 0):,}",
        f"<b>Total Revenue (Won):</b> ₹{lead_stats.get('total_revenue', 0):,}",
        f"<b>Conversion Rate:</b> {lead_stats.get('conversion_rate', 0)}%"
    ]
    for kpi in summary_kpis:
        para = Paragraph(kpi, styles['Normal'])
        para.wrapOn(p, 5 * inch, 10 * inch)
        para.drawOn(p, 1.2 * inch, y_position)
        y_position -= para.height + 5
    
    y_position -= 0.5 * inch

    # Active Leads by Stage
    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch, y_position, "Active Leads by Stage")
    y_position -= 0.4 * inch
    
    active_leads = [lead for lead in leads if lead.get('status') == 'Active']
    table_data = [["Lead Name", "Owner", "Value (INR)", "Stage"]]
    for lead in active_leads:
        table_data.append([
            lead.get('name', '-'),
            lead.get('owner', '-'),
            f"₹{lead.get('value', 0):,}",
            lead.get('stage', '-')
        ])
    
    table = Table(table_data, colWidths=[3*inch, 1.5*inch, 1.5*inch, 1*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey), ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'), ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12), ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))

    table_height = table.wrap(width - 2*inch, height)[1]
    table.drawOn(p, inch, y_position - table_height)
    y_position -= table_height + 0.5 * inch
    
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

# --- Background Task (Unchanged) ---
def generate_and_upload_report(report_id: str, report_name: str, report_type: str, user_email: str):
    print(f"BACKGROUND TASK STARTED for report {report_id} by {user_email}")
    try:
        all_projects = db_service.get_all_projects()
        all_leads = db_service.get_all_leads()
        project_stats = db_service.get_project_statistics()
        lead_stats = db_service.get_lead_statistics()
        all_metrics = { "project_stats": project_stats, "lead_stats": lead_stats }
        
        pdf_buffer = None
        if report_type == "Project Health":
            pdf_buffer = create_project_health_pdf(all_projects, user_email)
        elif report_type == "Leads & Sales":
            pdf_buffer = create_leads_sales_pdf(all_leads, lead_stats, user_email)
        else:
            pdf_buffer = create_summary_pdf(all_metrics, user_email)
        
        pdf_content = pdf_buffer.getvalue()
        file_path = f"generated/{report_id}.pdf"
        supabase.storage.from_("reports").upload(file=pdf_content, path=file_path, file_options={"content-type": "application/pdf", "upsert": "true"})
        public_url = supabase.storage.from_("reports").get_public_url(file_path)
        db_service.update_report_record(report_id, { "status": "Success", "download_url": public_url })
        print(f"BACKGROUND TASK COMPLETED SUCCESSFULLY for report {report_id}")

    except Exception as e:
        print(f"!!! BACKGROUND TASK FAILED for report {report_id} !!! ERROR: {e}")
        db_service.update_report_record(report_id, {"status": "Failed"})

# --- API Endpoints ---
@router.get("", response_model=List[Report])
async def get_reports(user: dict = Depends(get_current_user)):
    try:
        return db_service.get_all_reports()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/generate", response_model=Report, status_code=status.HTTP_202_ACCEPTED)
async def generate_new_report(
    report_data: ReportCreate,
    background_tasks: BackgroundTasks,
    user: dict = Depends(get_current_user)
):
    try:
        user_email = user.get('email', 'Unknown User')
        data_to_insert = report_data.model_dump()
        report_id = f"rep_{uuid4().hex[:8]}"
        data_to_insert["id"] = report_id
        data_to_insert["status"] = "Pending"
        data_to_insert["generated_by"] = user_email
        data_to_insert["generated_on"] = datetime.now().date().isoformat()
        
        new_report_record = db_service.create_report_record(data_to_insert)
        if not new_report_record:
            raise HTTPException(status_code=500, detail="Failed to create initial report record.")

        background_tasks.add_task(generate_and_upload_report, report_id, report_data.name, report_data.type, user_email)
        
        return Report.model_validate(new_report_record)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")

# --- NEW: Secure endpoint to delete a report ---
@router.delete("/{report_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_report(
    report_id: str,
    user: dict = Depends(get_current_user)
):
    """
    Deletes a report record from the database and the associated file from storage.
    """
    try:
        success = db_service.delete_report(report_id)
        if not success:
            # This handles the case where the report ID does not exist.
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Report with ID '{report_id}' not found.")
        # A 204 response has no body, so we return None.
        return None
    except Exception as e:
        # This will catch any unexpected errors from the database service.
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"An unexpected error occurred: {str(e)}")

